[package]
name = "oro-ser2mem-proc"
description = "Procedural macros for the ser2mem crate"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
proc-macro = true
test = false
bench = false

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.15", features = ["full"] }
