[package]
name = "oro-debug-pl011"
version.workspace = true
description = "PL011 UART driver for memory-mapped serial devices, used for Oro kernel debug output"
publish = false
edition = "2024"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[dependencies]
oro-sync.workspace = true

volatile-register.workspace = true

[lints]
workspace = true
