[package]
name = "orok-kernel"
version.workspace = true
description = "Oro operating system kernel"
publish = false
edition = "2024"
authors = ["Josh Junon (https//github.com/qix-)"]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"
autobins = false

build = "build.rs"

[lints]
workspace = true

[[bin]]
name = "oro-kernel"
path = "src/main.rs"
doc = false
test = false

[dependencies]
orok-arch.workspace = true
orok-boot.workspace = true
orok-test.workspace = true
