#:schema https://dystroy.org/bacon/.bacon.schema.json

# This is a configuration file for the bacon tool (cargo install bacon).
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml
#
# Its usage in the Oro Operating System kernel project is entirely
# optional, but it's a useful tool to run cargo check and/or clippy on
# all artifacts whilst developing the kernel.

default_job = "clippy"
env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "oro", "check", "--json"]
analyzer = "cargo_json"
need_stdout = true

[jobs.clippy]
command = ["cargo", "oro", "clippy", "--json"]
analyzer = "cargo_json"
need_stdout = true

[jobs.clippy-pkg]
command = ["cargo", "clippy", "-p", "orok-util-pkg"]
