[package]
name = "oro-kernel-root"
version = "0.1.0"
publish = false
edition = "2024"
license = "GPL-2.0 WITH Oro-syscall-exception"

[lib]
path = "utils/empty.rs"

[workspace]
resolver = "2"
default-members = ["utils/build-help"]
members = [
	"lib/*",
	"utils/*",
	"artifact/*/",
]

[workspace.dependencies]
orok_kernel.path = "lib/kernel"
orok_limine.path = "lib/limine"

[dependencies]
# Used by the limine bootloader
limine = "=0.6.5"

# Used by build utilities and proc macros
toml = "=1.1.2"
serde = { version = "=1.0.228", features = ["derive"] }
proc-macro2 = "=1.0.106"
quote = "=1.0.45"
clap = { version = "=4.6.1", features = ["derive", "string"] }
pathdiff = "=0.2.3"
flickzeug = "=0.5.1"
koto = "=0.16.1"

[package.metadata.oro.license-overrides]
koto.path = "../../.vendor-patches/LICENSE.koto"
koto_serde.path = "../../.vendor-patches/LICENSE.koto"
koto_parser.path = "../../.vendor-patches/LICENSE.koto"
koto_lexer.path = "../../.vendor-patches/LICENSE.koto"
koto_bytecode.path = "../../.vendor-patches/LICENSE.koto"
koto_memory.path = "../../.vendor-patches/LICENSE.koto"
koto_derive.path = "../../.vendor-patches/LICENSE.koto"
koto_runtime.path = "../../.vendor-patches/LICENSE.koto"
derive-name-macros.path = "../../.vendor-patches/LICENSE.derive-name-macros"


[workspace.lints.rust]
