[package]
name = "oro-limine-x86_64"
description = "Limine bootloader stub for the x86_64 architecture"
version = "0.0.0"
edition = "2024"
publish = false

build = "build.rs"

# NOTE: Limine's `ARCH` macro uses `x86-64` instead of the underscore,
#       so we adjust for that here.
[[bin]]
name = "oro-limine-x86-64"
path = "src/main.rs"

[dependencies]
orok-limine.workspace = true

[package.metadata.oro]
arch = "x86_64"
component = "bootloader"

[lints]
workspace = true
