[package]
name = "example-x86_64-tls-base"
description = "x86_64 TLS base (FS/GS) interface example"
version = "0.0.0"
publish = false
edition = "2021"

build = "build.rs"

[dependencies.oro]
path = "../../../oro"
features = ["module", "panic_debug_out_v0"]

[build-dependencies.oro]
path = "../../../oro"
features = ["build"]
default-features = false
