[package]
name = "oro-std"
version.workspace = true
description = "Interim Rust standard library shims for the Oro operating system"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []
oro = []
nightly = []

# `std` features
thread_id_value = []

# NOTE(qix-): This crate MUST NOT have any workspace (only) dependencies.
[dependencies]
oro = { version = "0.0.0", path = "../oro" }
