[package]
name = "oro-boot"
description = "Oro kernel boot protocol structures"
version = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
test = false
bench = false
