[package]
name = "oro"
version.workspace = true
description = "High level module API and build tooling."
publish = true
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []
nightly = []
runtime = []
module = ["runtime"]
build = []
panic_handler = []
panic_debug_out_v0 = ["panic_handler"]
