[package]
name = "oro"
version.workspace = true
description = "High level module API and build tooling."
publish = true
edition = "2024"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MIT OR Apache-2.0"

[lib]
doctest = false

[lints]
workspace = true

[features]
default = []
nightly = []
rustc-dep-of-std = [
	"core",
	"compiler_builtins",
	"compiler_builtins/rustc-dep-of-std",
	"cfg-if",
	"cfg-if/rustc-dep-of-std",
]

[dependencies]
cfg-if = { version = "*", optional = true }
core = { version = "*", optional = true, package = "rustc-std-workspace-core" }
compiler_builtins = { version = "*", optional = true }
