paths = [
    "vendor/android_system_properties",
    "vendor/anstream",
    "vendor/anstyle",
    "vendor/anstyle-parse",
    "vendor/anstyle-query",
    "vendor/anstyle-wincon",
    "vendor/autocfg",
    "vendor/bumpalo",
    "vendor/cc",
    "vendor/cfg-if",
    "vendor/chrono",
    "vendor/circular-buffer",
    "vendor/clap",
    "vendor/clap_builder",
    "vendor/clap_derive",
    "vendor/clap_lex",
    "vendor/colorchoice",
    "vendor/core-foundation-sys",
    "vendor/derive-name",
    "vendor/derive-name-macros",
    "vendor/dunce",
    "vendor/equivalent",
    "vendor/find-msvc-tools",
    "vendor/flickzeug",
    "vendor/futures-core",
    "vendor/futures-task",
    "vendor/futures-util",
    "vendor/hashbrown",
    "vendor/heck",
    "vendor/iana-time-zone",
    "vendor/iana-time-zone-haiku",
    "vendor/indexmap",
    "vendor/instant",
    "vendor/is_terminal_polyfill",
    "vendor/js-sys",
    "vendor/koto",
    "vendor/koto_bytecode",
    "vendor/koto_derive",
    "vendor/koto_lexer",
    "vendor/koto_memory",
    "vendor/koto_parser",
    "vendor/koto_runtime",
    "vendor/koto_serde",
    "vendor/libc",
    "vendor/limine",
    "vendor/log",
    "vendor/nu-ansi-term",
    "vendor/num-traits",
    "vendor/once_cell",
    "vendor/once_cell_polyfill",
    "vendor/paste",
    "vendor/pathdiff",
    "vendor/pin-project-lite",
    "vendor/proc-macro2",
    "vendor/quote",
    "vendor/rustc-hash",
    "vendor/rustversion",
    "vendor/saturating_cast",
    "vendor/serde",
    "vendor/serde_core",
    "vendor/serde_derive",
    "vendor/serde_spanned",
    "vendor/shlex",
    "vendor/slab",
    "vendor/smallvec",
    "vendor/strsim",
    "vendor/syn",
    "vendor/thiserror",
    "vendor/thiserror-impl",
    "vendor/toml",
    "vendor/toml_datetime",
    "vendor/toml_parser",
    "vendor/toml_writer",
    "vendor/unicode-ident",
    "vendor/unicode-segmentation",
    "vendor/unicode-width",
    "vendor/unicode-xid",
    "vendor/utf8parse",
    "vendor/wasm-bindgen",
    "vendor/wasm-bindgen-macro",
    "vendor/wasm-bindgen-macro-support",
    "vendor/wasm-bindgen-shared",
    "vendor/web-sys",
    "vendor/windows-core",
    "vendor/windows-implement",
    "vendor/windows-interface",
    "vendor/windows-link",
    "vendor/windows-result",
    "vendor/windows-strings",
    "vendor/windows-sys",
    "vendor/winnow",
]

[alias]
oro = [
    "run",
    "-p",
    "oro-kernel-build",
    "--offline",
    "--quiet",
    "--message-format",
    "short",
    "--",
]

[future-incompat-report]
frequency = "always"
