[alias]
oro = [
    "run",
    "-p",
    "orok-util-build",
    "--quiet",
    "--message-format",
    "short",
    "--",
]

pkg = [
	"run",
	"-p",
	"orok-util-pkg",
	"--"
]

[future-incompat-report]
frequency = "always"
