name: deps
description: Installs all dependencies needed for the CI runs
runs:
  using: "composite"
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy, rustc-dev, rust-src, llvm-tools-preview
    # Sigh. Cargo is severely broken. `build-std` is a nightmare.
    # The `std`/`core`/etc crates are not properly offline-able when
    # no other online builds have taken place to prime whatever they do
    # in `~/.cargo`. This is a workaround to get them properly cached.
    - name: Workaround for broken cargo/build-std
      shell: bash
      run: |
        cd artifact/x86_64-limine && cargo build
