[package]
name = "example-root-vbuf-demo"
description = "Example module that shows how to work with the ROOT_BOOT_VBUF_V0 interface."
version = "0.0.0"
publish = false
edition = "2021"

build = "build.rs"

[dependencies.oro]
path = "../../../oro"
features = ["module", "panic_debug_out_v0"]

[build-dependencies.oro]
path = "../../../oro"
features = ["build"]
default-features = false
