[package]
name = "example-test-ports"
description = "Temporary example module that tests ports."
version = "0.0.0"
publish = false
edition = "2021"

build = "build.rs"

[lib]
path = "src/lib.rs"

[[bin]]
name = "example-test-ports-producer"
path = "src/producer.rs"

[[bin]]
name = "example-test-ports-consumer"
path = "src/consumer.rs"

[dependencies.oro]
path = "../../../oro"
features = ["module", "nightly"]

[build-dependencies.oro]
path = "../../../oro"
features = ["build"]
default-features = false
