[package]
name = "example-hello-world"
description = "Example module that prints Hello World to the kernel logger."
version = "0.0.0"
publish = false
edition = "2021"

build = "build.rs"

[dependencies.oro]
path = "../../../oro"
features = ["module", "panic_debug_out_v0"]

[build-dependencies.oro]
path = "../../../oro"
features = ["build"]
default-features = false
