[package]
name = "oro-macro-proc"
version.workspace = true
description = "Proc macros for the Oro OS commons library (proc-macro portion)"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

build = "build.rs"

[lib]
proc-macro = true
doctest = false
doc = false # XXX(qix-): Temporary workaround for rustdoc regression

[dependencies]
syn = { workspace = true, features = ["full", "extra-traits"] }
quote.workspace = true
proc-macro2 = { workspace = true, features = ["proc-macro"] }
convert_case.workspace = true

[lints]
workspace = true
