[package]
name = "oro-sync"
version.workspace = true
description = "Synchronization primitives for the Oro kernel"
publish = false
edition = "2021"
authors = [
	"Josh Junon (https//github.com/qix-)"
]
homepage = "https://oro.sh"
repository = "https://github.com/oro-os/kernel"
license = "MPL-2.0"

[features]
default = ["reentrant_mutex"]
reentrant_mutex = []

[lib]
doctest = false

[dependencies]
oro-dbgutil.workspace = true

[lints]
workspace = true
