[package]
name = "orok-util-pkg"
description = "The Oro kernel packaging utility"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
oro-ramdisk = { workspace = true, features = ["encoder", "compression"] }
clap = { workspace = true, features = ["derive"] }
koto.workspace = true
isobemak.workspace = true
crc32fast.workspace = true
orok-util-common.workspace = true

[dev-dependencies]
oro-ramdisk = { workspace = true, features = [
	"encoder",
	"compression",
	"decoder",
	"decompression",
] }
