name: Build
on: [push, pull_request]

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install graphicsmagick libgraphicsmagick-dev
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          default: true
      - name: Build <D>
        uses: actions-rs/cargo@v1
        with:
          command: kbuild
      - name: Build <R>
        uses: actions-rs/cargo@v1
        with:
          command: kbuild
          args: --release
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Clippy
        uses: actions-rs/clippy@master
        with:
          args: --all-features --target triple/x86_64-oro.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install graphicsmagick libgraphicsmagick-dev
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          default: true
      - name: Generate Documentation
        uses: actions-rs/cargo@v1
        with:
          command: kdoc
          args: --config=build.rustdocflags=["--theme","${{ github.workspace }}/asset/docs/oro.css","--default-theme=oro"]
      - name: Copy Stub Index
        run: |
          cp ${{ github.workspace }}/asset/docs/index.html ${{ github.workspace }}/target/x86_64-oro/doc/index.html
      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v1.0.3
        with:
          path: ./target/x86_64-oro/doc
  deploy-docs:
    name: Deploy Documentation
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
