name: Build
on: [push, pull_request]

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install graphicsmagick libgraphicsmagick-dev
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          default: true
      - name: Build <D>
        run: make DEBUG=1
      - name: Build <R>
        run: make
      - name: Lint
        run: make lint
      - name: Clippy
        run: make clippy DEBUG=1
