name: Build
on: [push, pull_request]

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install graphicsmagick libgraphicsmagick-dev
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rustfmt, clippy, llvm-tools-preview, rust-src
          default: true
      - name: Build <D>
        uses: actions-rs/cargo@v1
        with:
          command: kbuild
      - name: Build <R>
        uses: actions-rs/cargo@v1
        with:
          command: kbuild
          args: --release
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check
      - name: Clippy
        uses: actions-rs/clippy@master
        with:
          args: --all-features --target triple/x86_64-oro.json -Zbuild-std=core,alloc -Zbuild-std-features=compiler-builtins-mem
