name: Build and Lint
on:
  push:
    branches:
      - master
      - kernel13
  pull_request:

env:
  RUST_BACKTRACE: full

jobs:
  lint-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Lint (rustfmt)
        run: cargo fmt --check
  lint-tomt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - run: cargo install tomt
      - name: Lint (tomt)
        run: tomt --check
  lint-clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Lint (clippy)
        run: make clippy CARGO_FLAGS="--profile ${{ matrix.profile }}"
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Lint (rustdoc)
        run: env RUSTFLAGS="-D warnings" RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --all
  build-x86_64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Build
        run: make x86_64 CARGO_FLAGS="--profile ${{ matrix.profile }}"
  build-aarch64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Build
        run: make aarch64 CARGO_FLAGS="--profile ${{ matrix.profile }}"
  build-riscv64:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: ["dev", "release"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Build
        run: make riscv64 CARGO_FLAGS="--profile ${{ matrix.profile }}"
