name: Build and Lint
on:
  push:
    branches:
      - master
      - kernel13
  pull_request:

env:
  RUST_BACKTRACE: full

jobs:
  lint-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Lint (rustfmt)
        run: cargo fmt --check
# NOTE: Disabled until the following is resolved:
#       https://github.com/rust-lang/cargo/issues/7058
#  check-vendor:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: 'true'
#      - uses: ./.github/actions/deps
#      - name: Check vendor
#        run: cargo oro vendor --check
#  check-udeps:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: 'true'
#      - uses: ./.github/actions/deps
#      - name: Check unused dependencies
#        run: cargo oro udeps
#  check-licenses:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: 'true'
#      - uses: ./.github/actions/deps
#      - name: Check licenses
#        run: cargo oro license --check
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - name: Build
        run: cargo oro build
      - name: Build (release)
        run: cargo oro build --release
      - name: Clippy
        run: cargo oro clippy
      - name: Package
        run: cargo pkg
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: target/pkg/*

  test-kernel-qemu:
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: ./.github/actions/deps
      - uses: ./.github/actions/oro-qemu
      # Get the artifacts from build-artifacts
      - uses: actions/download-artifact@v4
        with:
          name: kernel-artifacts
          path: target/pkg/
      - run: ls target/pkg/
